tailwind.config = {
            darkMode: "class",
            theme: {
                extend: {
                    "colors": {
                        "hub-bg": "#0B0E11",
                        "hub-card": "#16161a",
                        "hub-border": "#2d2d35",
                        "hub-text-primary": "#ffffff",
                        "hub-text-secondary": "#8b8b93",
                        "hub-primary": "#6366f1",
                        "hub-primary-hover": "#4f46e5",
                        "hub-input-bg": "#1c1c21",
                        "background": "#0e0e11",
                        "tertiary-dim": "#a88cfb",
                        "on-secondary-fixed": "#003271",
                        "on-surface": "#f0edf1",
                        "secondary-dim": "#699cff",
                        "on-secondary": "#001e4a",
                        "outline": "#767579",
                        "tertiary-fixed-dim": "#ad92ff",
                        "on-secondary-container": "#f7f7ff",
                        "secondary-fixed-dim": "#a9c4ff",
                        "on-primary-fixed": "#000000",
                        "primary-container": "#b28cff",
                        "primary-dim": "#8a4cfc",
                        "tertiary-fixed": "#baa3ff",
                        "on-tertiary-fixed": "#1d0054",
                        "secondary-fixed": "#bfd1ff",
                        "surface-container-highest": "#25252a",
                        "error-container": "#a70138",
                        "on-secondary-fixed-variant": "#004da8",
                        "inverse-surface": "#fcf8fd",
                        "on-surface-variant": "#acaaae",
                        "on-error-container": "#ffb2b9",
                        "primary": "#bd9dff",
                        "surface-container": "#19191d",
                        "surface-variant": "#25252a",
                        "on-primary": "#3c0089",
                        "error": "#ff6e84",
                        "tertiary": "#b299ff",
                        "inverse-primary": "#742fe5",
                        "surface-container-high": "#1f1f23",
                        "error-dim": "#d73357",
                        "on-tertiary-container": "#230062",
                        "secondary": "#699cff",
                        "on-primary-fixed-variant": "#390083",
                        "on-tertiary": "#31067e",
                        "secondary-container": "#005ac2",
                        "surface-tint": "#bd9dff",
                        "outline-variant": "#48474b",
                        "inverse-on-surface": "#555458",
                        "on-error": "#490013",
                        "surface-container-low": "#131316",
                        "on-primary-container": "#2e006c",
                        "primary-fixed-dim": "#a67aff",
                        "primary-fixed": "#b28cff",
                        "on-tertiary-fixed-variant": "#41208e",
                        "surface-container-lowest": "#000000",
                        "tertiary-container": "#a589f8",
                        "surface-dim": "#0e0e11",
                        "surface-bright": "#2c2c30",
                        "on-background": "#f0edf1",
                        "surface": "#0e0e11"
                    },
                    "backgroundImage": {
                        "gradient-primary": "linear-gradient(90deg, #8b5cf6 0%, #3b82f6 100%)",
                        "glow-radial": "radial-gradient(circle at 50% 50%, rgba(99, 102, 241, 0.15) 0%, rgba(11, 14, 17, 0) 50%)"
                    },
                    "borderRadius": {
                        "DEFAULT": "0.25rem",
                        "lg": "0.5rem",
                        "xl": "0.75rem",
                        "full": "9999px"
                    },
                    "fontFamily": {
                        "headline": ["Plus Jakarta Sans", "sans-serif"],
                        "body": ["Inter", "sans-serif"],
                        "label": ["Inter", "sans-serif"]
                    }
                }
            }
        }