/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/pages/**/*.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'hub-bg': 'var(--color-hub-bg)',
        'hub-card': 'var(--color-hub-card)',
        'hub-border': 'var(--color-hub-border)',
        'hub-text-primary': 'var(--color-hub-text-primary)',
        'hub-text-secondary': 'var(--color-hub-text-secondary)',
        'hub-primary': 'var(--color-hub-primary)',
        'hub-primary-hover': 'var(--color-hub-primary-hover)',
        'hub-input-bg': 'var(--color-hub-input-bg)',
        background: 'var(--color-background)',
        'tertiary-dim': 'var(--color-tertiary-dim)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'on-surface': 'var(--color-on-surface)',
        'secondary-dim': 'var(--color-secondary-dim)',
        'on-secondary': 'var(--color-on-secondary)',
        outline: 'var(--color-outline)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'primary-container': 'var(--color-primary-container)',
        'primary-dim': 'var(--color-primary-dim)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'error-container': 'var(--color-error-container)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'on-error-container': 'var(--color-on-error-container)',
        primary: 'var(--color-primary)',
        'surface-container': 'var(--color-surface-container)',
        'surface-variant': 'var(--color-surface-variant)',
        'on-primary': 'var(--color-on-primary)',
        error: 'var(--color-error)',
        tertiary: 'var(--color-tertiary)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'error-dim': 'var(--color-error-dim)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        secondary: 'var(--color-secondary)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'secondary-container': 'var(--color-secondary-container)',
        'surface-tint': 'var(--color-surface-tint)',
        'outline-variant': 'var(--color-outline-variant)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        'on-error': 'var(--color-on-error)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'surface-dim': 'var(--color-surface-dim)',
        'surface-bright': 'var(--color-surface-bright)',
        'on-background': 'var(--color-on-background)',
        surface: 'var(--color-surface)',
        store: {
          primary: 'var(--theme-primary)',
          secondary: 'var(--theme-secondary)',
          bg: 'var(--theme-bg)',
          text: 'var(--theme-text-primary)',
          muted: 'var(--theme-text-secondary)',
        },
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(90deg, #8b5cf6 0%, #3b82f6 100%)',
        'glow-radial':
          'radial-gradient(circle at 50% 50%, rgba(99, 102, 241, 0.15) 0%, rgba(11, 14, 17, 0) 50%)',
      },
      spacing: {
        'space-1': 'var(--space-1)',
        'space-2': 'var(--space-2)',
        'space-3': 'var(--space-3)',
        'space-4': 'var(--space-4)',
        'space-5': 'var(--space-5)',
        'space-6': 'var(--space-6)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
      borderRadius: {
        sm: 'var(--border-radius-sm)',
        md: 'var(--border-radius-md)',
        lg: 'var(--border-radius-lg)',
        pill: 'var(--border-radius-pill)',
      },
      fontSize: {
        'h1': ['2.5rem', { lineHeight: '3rem', fontWeight: '700' }],
        'h2': ['2rem', { lineHeight: '2.5rem', fontWeight: '700' }],
        'h3': ['1.75rem', { lineHeight: '2.25rem', fontWeight: '600' }],
        'h4': ['1.5rem', { lineHeight: '2rem', fontWeight: '600' }],
        'h5': ['1.25rem', { lineHeight: '1.75rem', fontWeight: '600' }],
        'h6': ['1rem', { lineHeight: '1.5rem', fontWeight: '600' }],
        'body-1': ['1rem', { lineHeight: '1.5rem', fontWeight: '400' }],
        'body-2': ['0.875rem', { lineHeight: '1.25rem', fontWeight: '400' }],
        'button': ['0.875rem', { lineHeight: '1.25rem', fontWeight: '600' }],
      },
      fontFamily: {
        headline: 'var(--font-family-headline)',
        body: 'var(--font-family-base)',
        label: 'var(--font-family-base)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
