/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/pages/**/*.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'hub-bg': 'var(--color-hub-bg)',
        'hub-card': 'var(--color-hub-card)',
        'hub-border': 'var(--color-hub-border)',
        'hub-text-primary': 'var(--color-hub-text-primary)',
        'hub-text-secondary': 'var(--color-hub-text-secondary)',
        'hub-primary': 'var(--color-hub-primary)',
        'hub-primary-hover': 'var(--color-hub-primary-hover)',
        'hub-input-bg': 'var(--color-hub-input-bg)',
        background: 'var(--color-background)',
        'tertiary-dim': 'var(--color-tertiary-dim)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'on-surface': 'var(--color-on-surface)',
        'secondary-dim': 'var(--color-secondary-dim)',
        'on-secondary': 'var(--color-on-secondary)',
        outline: 'var(--color-outline)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'primary-container': 'var(--color-primary-container)',
        'primary-dim': 'var(--color-primary-dim)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'error-container': 'var(--color-error-container)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'on-error-container': 'var(--color-on-error-container)',
        primary: 'var(--color-primary)',
        'surface-container': 'var(--color-surface-container)',
        'surface-variant': 'var(--color-surface-variant)',
        'on-primary': 'var(--color-on-primary)',
        error: 'var(--color-error)',
        tertiary: 'var(--color-tertiary)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'error-dim': 'var(--color-error-dim)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        secondary: 'var(--color-secondary)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'secondary-container': 'var(--color-secondary-container)',
        'surface-tint': 'var(--color-surface-tint)',
        'outline-variant': 'var(--color-outline-variant)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        'on-error': 'var(--color-on-error)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'surface-dim': 'var(--color-surface-dim)',
        'surface-bright': 'var(--color-surface-bright)',
        'on-background': 'var(--color-on-background)',
        surface: 'var(--color-surface)',
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(90deg, #8b5cf6 0%, #3b82f6 100%)',
        'glow-radial':
          'radial-gradient(circle at 50% 50%, rgba(99, 102, 241, 0.15) 0%, rgba(11, 14, 17, 0) 50%)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
